[build]
  publish = "docs"
  functions = "netlify/functions"

  # Optional: For redirects or headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  MONGODB_URI = "mongodb+srv://bradbehlow:rJ48Bbud5h2Iq1Az@sendvid.fc7i3.mongodb.net/"